import { AgentBrowserIcon } from '@/components/icons'
import { AuthMode, type BlockConfig, IntegrationType } from '@/blocks/types'
import type { AgentBrowserExecuteResponse } from '@/tools/agent_browser/types'

export const AgentBrowserBlock: BlockConfig<AgentBrowserExecuteResponse> = {
  type: 'agent_browser',
  name: 'Agent Browser CLI',
  description: 'Run agent-browser CLI scripts inside a workflow',
  authMode: AuthMode.ApiKey,
  longDescription:
    'Integrate the agent-browser CLI into the workflow toolbar. Execute a multiline browser automation script, reuse sessions across commands, and pass provider API keys through workflow environment variables.',
  docsLink: 'https://agent-browser.dev/commands',
  category: 'tools',
  integrationType: IntegrationType.Automation,
  tags: ['web-scraping', 'automation', 'agentic'],
  bgColor: '#FF6A2B',
  icon: AgentBrowserIcon,
  subBlocks: [
    {
      id: 'script',
      title: 'Script',
      type: 'long-input',
      rows: 12,
      required: true,
      placeholder: `open https://example.com
snapshot -i --compact
click @e2
fill @e3 "user@example.com"
screenshot`,
      tooltip:
        'Use one agent-browser command per line. Global browser settings belong in the advanced fields below.',
    },
    {
      id: 'session',
      title: 'Session',
      type: 'short-input',
      placeholder: 'checkout-flow',
      description: 'Optional shared session name for all commands in this block run',
    },
    {
      id: 'provider',
      title: 'Provider',
      type: 'dropdown',
      options: [
        { label: 'Local Browser', id: 'local' },
        { label: 'Browserbase', id: 'browserbase' },
        { label: 'Browser Use', id: 'browseruse' },
        { label: 'iOS Simulator', id: 'ios' },
      ],
      value: () => 'local',
      description: 'Optional remote provider used by agent-browser',
    },
    {
      id: 'cliEnvironment',
      title: 'CLI Environment',
      type: 'table',
      columns: ['Key', 'Value'],
      description:
        'Pass env vars to the CLI process. Use workflow env refs like {{BROWSERBASE_API_KEY}} or {{BROWSER_USE_API_KEY}} in Value cells.',
    },
    {
      id: 'headed',
      title: 'Headed',
      type: 'switch',
      mode: 'advanced',
      description: 'Launch a visible browser window instead of headless mode',
    },
    {
      id: 'profile',
      title: 'Profile Path',
      type: 'short-input',
      mode: 'advanced',
      placeholder: '~/.agent-browser/profiles/default',
      description: 'Persistent browser profile directory passed via --profile',
    },
    {
      id: 'executablePath',
      title: 'Executable Path',
      type: 'short-input',
      mode: 'advanced',
      placeholder: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      description: 'Custom Chrome or Chromium binary path',
    },
    {
      id: 'cdp',
      title: 'CDP URL',
      type: 'short-input',
      mode: 'advanced',
      placeholder: 'ws://127.0.0.1:9222/devtools/browser/...',
      description: 'Attach to an existing browser through the Chrome DevTools Protocol',
    },
    {
      id: 'autoConnect',
      title: 'Auto Connect',
      type: 'switch',
      mode: 'advanced',
      description: 'Let agent-browser auto-connect to an existing session when possible',
    },
    {
      id: 'userAgent',
      title: 'User Agent',
      type: 'short-input',
      mode: 'advanced',
      placeholder: 'Mozilla/5.0 ...',
      description: 'Override the browser user agent string',
    },
    {
      id: 'proxy',
      title: 'Proxy',
      type: 'short-input',
      mode: 'advanced',
      placeholder: 'http://user:pass@host:port',
      description: 'Proxy server URL',
    },
    {
      id: 'headers',
      title: 'Headers',
      type: 'code',
      mode: 'advanced',
      language: 'json',
      placeholder: '{\n  "Authorization": "Bearer <token>"\n}',
      description: 'Default request headers passed via --headers as a JSON object',
    },
    {
      id: 'browserArgs',
      title: 'Browser Args',
      type: 'short-input',
      mode: 'advanced',
      placeholder: '--disable-gpu --window-size=1440,900',
      description: 'Additional browser launch args passed through --args',
    },
    {
      id: 'timeoutMs',
      title: 'Timeout (ms)',
      type: 'short-input',
      mode: 'advanced',
      placeholder: '300000',
      description: 'Per-command timeout in milliseconds',
    },
    {
      id: 'allowFileAccess',
      title: 'Allow File Access',
      type: 'switch',
      mode: 'advanced',
      description: 'Enable file:// access in the browser',
    },
    {
      id: 'ignoreHttpsErrors',
      title: 'Ignore HTTPS Errors',
      type: 'switch',
      mode: 'advanced',
      description: 'Ignore TLS certificate validation errors',
    },
    {
      id: 'debug',
      title: 'Debug',
      type: 'switch',
      mode: 'advanced',
      description: 'Enable verbose agent-browser CLI logging',
    },
  ],
  tools: {
    access: ['agent_browser_execute'],
  },
  inputs: {
    script: { type: 'string', description: 'Multiline agent-browser CLI script' },
    session: { type: 'string', description: 'Optional session shared across commands' },
    provider: { type: 'string', description: 'Optional remote provider name' },
    cliEnvironment: { type: 'json', description: 'Environment variables passed to the CLI' },
    headed: { type: 'boolean', description: 'Launch a headed browser window' },
    profile: { type: 'string', description: 'Persistent browser profile path' },
    executablePath: { type: 'string', description: 'Custom browser executable path' },
    cdp: { type: 'string', description: 'Existing browser CDP endpoint' },
    autoConnect: { type: 'boolean', description: 'Auto-connect to an existing session' },
    userAgent: { type: 'string', description: 'Custom browser user agent' },
    proxy: { type: 'string', description: 'Proxy server URL' },
    headers: { type: 'json', description: 'Default request headers' },
    browserArgs: { type: 'string', description: 'Additional browser launch args' },
    timeoutMs: { type: 'string', description: 'Per-command timeout in milliseconds' },
    allowFileAccess: { type: 'boolean', description: 'Allow file URL access' },
    ignoreHttpsErrors: { type: 'boolean', description: 'Ignore HTTPS certificate errors' },
    debug: { type: 'boolean', description: 'Enable verbose CLI logging' },
  },
  outputs: {
    success: { type: 'boolean', description: 'Whether the full script completed successfully' },
    session: { type: 'string', description: 'Session used for the run' },
    commandCount: { type: 'number', description: 'Number of CLI commands executed' },
    finalResult: { type: 'json', description: 'Parsed output from the last CLI command' },
    imageFile: {
      type: 'file',
      description: 'Latest screenshot or diff image captured during the script',
    },
    imageFiles: {
      type: 'file[]',
      description: 'All screenshot and diff images captured during the script',
    },
    results: { type: 'json', description: 'Per-command execution results' },
  },
}
